apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 10m
  chart:
    spec:
      chart: community-operator
      version: '0.11.0'
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: mongodb
      interval: 10m
