apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 10m
  chart:
    spec:
      chart: postgres-operator
      version: '1.13.0'
      sourceRef:
        kind: HelmRepository
        name: postgres
        namespace: postgres
      interval: 10m
