apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: celonis-poc
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/jmcarbo/celonis-poc
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: celonis-poc-base
  namespace: default
spec:
  interval: 10m
  wait: true
  sourceRef:
    kind: GitRepository
    name: celonis-poc
  path: "./manifests/base"
  prune: true
  timeout: 1m
  retryInterval: 30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: celonis-poc-dbs
  namespace: default
spec:
  interval: 10m
  wait: true
  dependsOn:
    - name: celonis-poc-base
  sourceRef:
    kind: GitRepository
    name: celonis-poc
  path: "./manifests/dbs"
  prune: true
  timeout: 1m
  retryInterval: 30s
