apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: celonis-poc
  namespace: default
spec:
  interval: 1m0s
  url: https://github.com/jmcarbo/celonis-poc
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: celonis-poc-base
  namespace: default
spec:
  interval: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: celonis-poc
  path: "./manifests/base"
  prune: true
  timeout: 15m
  retryInterval: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: celonis-poc-dbs
  namespace: default
spec:
  interval: 2m
  wait: true
  dependsOn:
    - name: celonis-poc-base
  sourceRef:
    kind: GitRepository
    name: celonis-poc
  path: "./manifests/dbs"
  prune: true
  timeout: 5m
  retryInterval: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: celonis-poc-extra
  namespace: default
spec:
  interval: 2m
  wait: true
  dependsOn:
    - name: celonis-poc-base
  sourceRef:
    kind: GitRepository
    name: celonis-poc
  path: "./manifests/extras"
  prune: true
  timeout: 2m
  retryInterval: 2m
