repositories:
- name: jetstack 
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  installed: true
  chart: jetstack/cert-manager
  values:
  - crds:
      enabled: true
  - extraArgs:
      - --enable-gateway-api
