repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts


releases:
- name: prometheus-community
  namespace: prometheus
  chart: prometheus-community/prometheus
