repositories:
- name: nats
  url: https://nats-io.github.io/k8s/helm/charts/

releases:
- name: nats
  namespace: nats
  chart: nats/nats
  version: 1.2.6
  values:
  - config:
      cluster:
        enabled: true
        replicas: 3
        name: nats2
      jetstream:
        enabled: true
        fileStore:
          pvc:
            size: 10Gi

  - container:
      env:
      # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
      # should be ~90% of memory limit
      GOMEMLIMIT: 7GiB
    merge:
      # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
      resources:
        requests:
          cpu: "2"
          memory: 8Gi
        limits:
          cpu: "2"
          memory: 8Gi

  - podTemplate:
      topologySpreadConstraints:
        kubernetes.io/hostname:
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule


