repositories:
- name: equinixmetal
  url: https://helm.equinixmetal.com
  #- name: ngrok
    # url: https://charts.ngrok.com
- name: incubator
  url: https://charts.helm.sh/incubator
- name: bedag
  url: https://bedag.github.io/helm-charts
- name: temporal
  url: https://go.temporal.io/helm-charts
- name: bitnami
  url: registry-1.docker.io/bitnamicharts
  oci: true
- name: mongodb
  url: https://mongodb.github.io/helm-charts
- name: nats
  url: https://nats-io.github.io/k8s/helm/charts/

releases:

- name: community-operator 
  namespace: mongodb
  chart: mongodb/community-operator

  #- name: mongodb
  #  namespace: mongodb
  #  chart: bitnami/mongodb
  #  version: 16.0.0
  #  set:
  #  - name: auth.rootPassword
  #    value: "root"
  #  - name: auth.username
  #    value: "user"
  #  - name: auth.password
  #    value: "password"
  #  - name: auth.database
  #    value: "admin"


  #- name: redis
  #  namespace: redis
  #  chart: bitnami/redis
  #  version: 20.1.7

- name: keycloak
  namespace: keycloak
  chart: bedag/raw
  values:
  - resources:
    - apiVersion: v1
      data:
        bla: bla 
      kind: ConfigMap
      metadata:
        name: bla
        namespace: keycloak
    - apiVersion: v1
      kind: Service
      metadata:
        name: keycloak
        namespace: keycloak
        labels:
          app: keycloak
      spec:
        ports:
          - name: http
            port: 8080
            targetPort: 8080
        selector:
          app: keycloak
        type: LoadBalancer
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: keycloak
        namespace: keycloak
        labels:
          app: keycloak
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: keycloak
        template:
          metadata:
            labels:
              app: keycloak
          spec:
            containers:
              - name: keycloak
                image: quay.io/keycloak/keycloak:26.0.0
                args: ["start-dev"]
                env:
                  - name: KEYCLOAK_ADMIN
                    value: "admin"
                  - name: KEYCLOAK_ADMIN_PASSWORD
                    value: "admin"
                  - name: KC_PROXY
                    value: "edge"
                ports:
                  - name: http
                    containerPort: 8080
                readinessProbe:
                  httpGet:
                    path: /realms/master
                    port: 8080
