apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chartRef:
    kind: OCIRepository
    name: bitnami-redis
    namespace: redis
  interval: 10m
