apiVersion: v1
kind: Namespace
metadata:
  name: temporal
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: temporal
  namespace: temporal
spec:
  interval: 1m
  url:  https://go.temporal.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
  namespace: temporal
spec:
  interval: 10m
  chart:
    spec:
      chart: temporal
      version: '>=0.50.0'
      sourceRef:
        kind: HelmRepository
        name: temporal
        namespace: temporal
      interval: 10m
  values:
    prometheus:
      enabled: false
    grafana:
      enabled: false
    elasticsearch:
      enabled: true
