apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus
      version: '>=25.28.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      interval: 10m