apiVersion: v1
kind: Namespace
metadata:
  name: opal
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: permitio
  namespace: opal
spec:
  interval: 1m
  url: https://permitio.github.io/opal-helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opal
  namespace: opal
spec:
  interval: 10m
  chart:
    spec:
      chart: opal
      version: '>=0.0.0'
      sourceRef:
        kind: HelmRepository
        name: permitio
        namespace: opal
      interval: 10m
  values:
    server:
      port: 7002
      policyRepoUrl: "https://github.com/permitio/opal-example-policy-repo"
      policyRepoSshKey: null
      policyRepoClonePath: null
      policyRepoMainBranch: null
      pollingInterval: 30
      dataConfigSources:
        # Option #1 - No data sources
        config:
          entries: [ ]
    client:
      extraEnv:
        OPAL_OPA_HEALTH_CHECK_POLICY_ENABLED: True
        OPAL_DATA_UPDATER_ENABLED: False